spring:
  datasource:
    url: jdbc:mysql://lib-seat-db-b-mysql.ns-51r2zsdm.svc:3306/lib_seat?zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 9nc44sl7
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  flyway:
    enabled: true
    clean-disabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
    validate-on-migrate: true
    # 添加以下配置来解决锁表问题
    lock-retry-count: 10
    lock-retry-interval: 1s
    # 禁用表锁
    lock-table: false
    # 启用清理功能
    clean-on-validation-error: true
  task:
    scheduling:
      enabled: true